MppMonitor/Models/PaymentSuccessRate.cs
namespace MppMonitor.Models
{
    public class PaymentSuccessRate
    {
        public double AuthRate { get; set; }
    }
}

MppMonitor/Models/RestApi/ArQueueSize.cs
using System;
using System.Runtime.Serialization;

namespace MppMonitor.Models.RestApi
{
    [DataContract(Name = "repo")]
    public class ArQueueSize
    {
        [DataMember(Name = "Amount")]
        public int Size { get; set; }

        [DataMember(Name = "DateTime")]
        public string Time { get; set; }
    }
}

MppMonitor/Models/RestApi/PaymentAuthRate.cs
using System;
using System.Runtime.Serialization;

namespace MppMonitor.Models.RestApi
{
    [DataContract(Name = "repo")]
    public class PaymentAuthRate
    {
        [DataMember(Name = "IssuingOrganization")]
        public string IssuingOrganization { get; set; }

        [DataMember(Name = "First_CountOfAuthorisations")]
        public int First_CountOfAuthorisations { get; set; }        

        [DataMember(Name = "First_CountOfDeclines")]
        public int First_CountOfDeclines { get; set; }

        [DataMember(Name = "First_CountOfErrors")]
        public int First_CountOfErrors { get; set; }

        [DataMember(Name = "Renew_CountOfAuthorisations")]
        public int Renew_CountOfAuthorisations { get; set; }

        [DataMember(Name = "Renew_CountOfDeclines")]
        public int Renew_CountOfDeclines { get; set; }

        [DataMember(Name = "Renew_CountOfErrors")]
        public int Renew_CountOfErrors { get; set; }

        [DataMember(Name = "Retry_CountOfAuthorisations")]
        public int Retry_CountOfAuthorisations { get; set; }

        [DataMember(Name = "Retry_CountOfDeclines")]
        public int Retry_CountOfDeclines { get; set; }

        [DataMember(Name = "Retry_CountOfErrors")]
        public int Retry_CountOfErrors { get; set; }

        [DataMember(Name = "PaymentProvider")]
        public string PaymentProvider { get; set; }
    }
}

MppMonitor/Controllers/ArQueueSizeController.cs
using Microsoft.AspNetCore.Mvc;

namespace MppMonitor.Controllers
{
    public class ArQueueSizeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MppMonitor/Controllers/PaymentAuthRateController.cs
using Microsoft.AspNetCore.Mvc;
using MppMonitor.ViewModel;

namespace MppMonitor.Controllers
{
    public class PaymentAuthRateController : Controller
    {
        public IActionResult Index(string paymentProvider)
        {
            return View(new PaymentProviderViewModel { PaymentProvider = paymentProvider ?? "Overall" });
        }
    }
}

MppMonitor/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MppMonitor.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

MppMonitor/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MppMonitor.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

MppMonitor/ViewComponents/ArQueueSizeViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace MppMonitor.ViewComponents
{
    public class ArQueueSizeViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

MppMonitor/ViewComponents/PaymentAuthRateViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MppMonitor.ViewModel;

namespace MppMonitor.ViewComponents
{
    public class PaymentAuthRateViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(string paymentProvider)
        {
            return View(new PaymentProviderViewModel { PaymentProvider = paymentProvider ?? "Overall" });
        }
    }
}

MppMonitor/Pages/Index.cshtml
@page

@{ViewData["Title"] = "Monitors";}

<script src="~/lib/signalr/signalr.js"></script>

<div class="grid">
    @await Component.InvokeAsync("ArQueueSize")
    @await Component.InvokeAsync("PaymentAuthRate", "Overall")
    @await Component.InvokeAsync("PaymentAuthRate", "SecPay")
    @await Component.InvokeAsync("PaymentAuthRate", "Realex")
</div>

MppMonitor/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mpp Monitor</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content fullBody">
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

MppMonitor/Views/ArQueueSize/Index.cshtml
@{
    Layout = "_Layout";
}

<script src="~/lib/signalr/signalr.js"></script>

@{
    ViewData["Title"] = "Auto Renew Queue Size";
}

<div class="single fullBody">
    @await Component.InvokeAsync("ArQueueSize")
</div>

MppMonitor/Views/PaymentAuthRate/Index.cshtml
@model MppMonitor.ViewModel.PaymentProviderViewModel

@{
    Layout = "_Layout";
}

<script src="~/lib/signalr/signalr.js"></script>

@{
    ViewData["Title"] = "Auth Rates";
}

<div class="single fullBody">
    @await Component.InvokeAsync("PaymentAuthRate", Model.PaymentProvider)
</div>

MppMonitor/Views/Shared/Components/ArQueueSize/Default.cshtml
<div class="container monitor">
    <div class="row fullBody">
        <div class="centreTextContainer  alert" id="ArQueueSizeContainer">
            <span>
                <p class="bigFont" id="ArQueueSizeSize">Waiting for update</p>
                <p class="smallFont" id="ArQueueSizeTime" />
            </span>
            <p class="smallerFont">Auto Renew Queue Size</p>
        </div>
    </div>
</div>

<script src="~/js/arQueueSize.js"></script>

MppMonitor/Views/Shared/Components/PaymentAuthRate/Default.cshtml
@model MppMonitor.ViewModel.PaymentProviderViewModel

<div class="container monitor">
    <div class="row fullBody">
        <div class="centreTextContainer caution" id="PaymentAuthRateContainer-@Model.PaymentProvider">
            <span>
                <p class="bigFont" id="PaymentAuthRateRate-@Model.PaymentProvider">Waiting for update</p>
                <p class="smallFont" id="PaymentAuthRatePaymentProvider-@Model.PaymentProvider" />
                <p class="smallerFont">Payment Authentication Rates</p>
            </span>
        </div>
    </div>
</div>

<script src="~/js/paymentAuthRate.js"></script>